Small changes in html
commIT-Group/Advice-generator-app pull request #40
Opened 2023-04-02 16:37 UTC by car2t

Switch utf-8 meta element by <meta http-equiv="Content-type" content="text/html; charset=UTF-8"> to try to fix the german word issue.

Change the value of the min-width attribute in the source element to 440px; the width of the bigger SVG image.

2023-04-02 17:06 UTC, nikkehtine approved these changes

2023-04-03 09:59 UTC, WitchDevelops approved these changes

2023-04-03 11:29 UTC, nikkehtine requested changes
The commit says "replace", but it doesn't replace anything, it only deletes one line

2023-04-04 01:00 UTC, caesiumtea approved these changes

2023-04-04 11:54 UTC, merged