HTML a few small changes, read below or commits
commIT-Group/Advice-generator-app pull request #42
Opened 2023-04-05 11:39 UTC by car2t

Hi all 

I did this in the HTML document.

1 - Add alt attribute with an empty string value to all the images

2 - Switch the p.footer-text for an address element

3 - Delete final periods in the footer. Visually annoy, since it looked like headings with a final dot.

I hope you like it.

2023-04-05 19:25 UTC, WitchDevelops commented on index.html
> +    <link rel="icon" type="image/png" sizes="32x32" href="./images/favicon-32x32.png" />
only formatting, not really necessary

2023-04-05 19:27 UTC, WitchDevelops commented on index.html
> +    <div id="web-app-wrapper">
why

2023-04-05 19:37 UTC, WitchDevelops commented
> 1 - Add alt attribute with an empty string value to all the images
I don't see this change. There is `alt` on the dice (not an empty string) and no `alt` on the divider.

> 2 - Switch the p.footer-text for an address element
It's a good idea, but I don't see this in the final code.

> 3 - Delete final periods in the footer. Visually annoy, since it looked like headings with a final dot.
ok, I'm fine with that

> 4 - I have added a div wrapping the whole page: <div id="web-app-wrapper">.
I want to try putting in the general layout and making the body a small grid container using grid-template-columns: 1rem 1fr 1rem;. I think it will look better.
I don't understand the reason why do you want to do this. Can you explain why do you think it's a good idea? To put the whole `body` in a `div` element? If you want to make it into a grid container, why not declare it on the `body`?

2023-04-05 19:39 UTC, WitchDevelops requested changes
Please provide a reason for those changes :)

2023-04-06 07:58 UTC, car2t commented
Hi Domi

> > 1 - Add alt attribute with an empty string value to all the images
> 
**> I don't see this change. There is `alt` on the dice (not an empty string) and no `alt` on the divider.** 

_It looks that I have missed a few. Oops! Yeah! You are right, maybe we can add alt="" to dividers and more descriptive one to the image. 
Also I have forgot about adding `width` and `height` attributes too; better give it in advance to the browser_

> > > 2 - Switch the p.footer-text for an address element
> 
> **It's a good idea, but I don't see this in the final code.**

_Ok, never mind, not important._

> > 3 - Delete final periods in the footer. Visually annoy, since it looked like headings with a final dot.
> 
> **ok, I'm fine with that** _Cool!_ ;D
> 
> > 4 - I have added a div wrapping the whole page: .
> > I want to try putting in the general layout and making the body a small grid container using grid-template-columns: 1rem 1fr > 1rem;. I think it will look better.
> 
> **I don't understand the reason why do you want to do this. Can you explain why do you think it's a good idea? To put the whole `body` in a `div` element? If you want to make it into a grid container, why not declare it on the `body`?**

_I can test on my own, not important, we can leave it as it is. No problemo._

Thank you Domi for taking your time to review this. :D

2023-04-06 13:18 UTC, closed without merging

2023-04-06 13:22 UTC, car2t commented
I will wait for others speak and see what new things we can do. 
Also I probably will delete commits or directly the branch, not necessary for now, right?

By for now

2023-04-06 19:18 UTC, caesiumtea commented
@car2t 
It looks like your final commit in the `html` branch (commit 98245a2cb8e101fef36203b5b41d81c0fdb7f993) actually undoes the changes in your previous couple of commits! I suggst we reset the `html` branch to commit 25a7beca0f089903b5342616e8682f421a1dd0cd and then open a PR on that.

> 1 - Add alt attribute with an empty string value to all the images

Good catch, yes, those dividers should definitely have `alt=""` on them! But don't change the alt text on the dice button--that one is NOT purely decorative. The alt text should indicate that it serves a "randomize" function, because that's the meaning that the dice symbol expresses.

> 2 - Switch the p.footer-text for an address element

Sounds good to me
 
> 3 - Delete final periods in the footer. Visually annoy, since it looked like headings with a final dot.

Sure, I agree it looked a little odd.

> 4 - I have added a `div `wrapping the whole page: `<div id="web-app-wrapper">`. I want to try putting in the general layout and making the body a small grid container using `grid-template-columns: 1rem 1fr 1rem;`. I think it will look better.

Go ahead and try it out, because I can't figure out what difference it will make just by imagining it haha. But maybe in a separate branch from these alt text and footer changes.

@WitchDevelops 
> I don't understand the reason why do you want to do this. Can you explain why do you think it's a good idea? To put the whole body in a div element? If you want to make it into a grid container, why not declare it on the body?

Is it just because it's good to keep semantic elements separate from style-related elements? idk